### ISSUE TITLE
Nerve is unreliable under load

### ISSUE THREAD

**Issue by alexanderdean** [gjritter/nerve#4]
Please see: http://stackoverflow.com/questions/4800107/node-js-script-using-nerve-runs-controller-multiple-times-for-one-request

**Comment by gjritter** [comment]
I think the problem you're seeing is related to how apache bench works, and is not a problem in nerve or your app.

I added this comment to the question on stack overflow, and will add it here as well:

It looks like Apache Bench can send more requests than you've requested. "The ‘ab’ tool does in fact measure the completion of its requests properly, but it may actually send more requests than you ask it to. That’s because it counts replies not requests." See this blog post for more info: http://adrianotto.com/2010/05/apache-benchmark-ab-is-not-exact/

**Comment by alexanderdean** [comment]
I concur - I've performed the same test with Express and encountered the same issue. Closing this.

**Comment by gjritter** [comment]
Thanks for confirming!
